version: "1.0"
stages:
  - "deploy"
  - "clone"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  deploy:
    title: Deploy packages
    stage: "deploy"
    type: freestyle
    working_directory: "./activity-brainstorm"
    arguments:
      image: "node:latest"
      commands:
        - yarn
        - npm i -g firebase-tools
        - yarn run release
        - yarn build
        - firebase deploy --token "$FIREBASE_KEY"
    when:
      branch:
        only:
          - master
