version: "1.0"
stages:
  - "deploy"
  - "clone"

steps:
  test:
    title: Deploy packages
    stage: "deploy"
    type: freestyle
    working_directory: "${{CF_REPO_NAME}}"
    arguments:
      image: "node:latest"
      commands:
        - echo "-------"
        - ls -la /codefresh/volume/
        - pwd
        - ls -la
        # - ls -la node_modules

  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  deploy:
    title: Deploy packages
    stage: "deploy"
    type: freestyle
    working_directory: ${{CF_REPO_NAME}}
    arguments:
      image: "node:latest"
      commands:
        - echo "here"
        # - ls -la node_modules
        - echo $FIREBASE_CONFIG > src/firebaseConfig.js
        - echo $FIREBASE_CONFIG > functions/src/firebaseConfig.js
        - echo $FUNCTIONS_ENV > functions/src/env.ts
        - yarn
        - yarn run release
        - ls -la /codefresh/volume/
        - yarn build
        - ls -la /codefresh/volume/
        - echo "Firebase Start"
        - npm i -g firebase-tools
        - firebase deploy --token "$FIREBASE_KEY"
        - echo "Firebase end"
    when:
      branch:
        only:
          - master
